# Generated by Django 6.0.4 on 2026-05-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_satus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='satus',
            new_name='status',
        ),
    ]
